@startuml
actor Keeper
participant "FeedingSchedule" as Schedule
participant "Animal"
participant "Enclosure"

' Feeding
alt User chooses animal menu
    Keeper -> Animal : ask for FeedingSchedule
    Animal --> Keeper : FeedindSchedule
    activate Schedule
    Keeper -> Schedule : check_feeding_schedule()
    Schedule --> Keeper : food, time
    deactivate Schedule

    Keeper -> Animal : feed()
    Animal -> Animal : update_feeding_history()

else
end alt

' Cleaning
alt User chooses enclosure menu
    Keeper -> Enclosure : clean()
    Enclosure -> Enclosure : change_status(String)
else
end alt
@enduml
